# Generated by Django 4.1 on 2024-04-20 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('trans_languages', models.JSONField(blank=True, default=dict, null=True, verbose_name='Translation Languages')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_languages', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('salary', models.CharField(max_length=255, verbose_name='Salary')),
                ('vacancy_number', models.CharField(max_length=255, verbose_name='Vacancy Number')),
                ('no_of_jobs', models.IntegerField(verbose_name='Counts')),
                ('organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('contract_duration', models.CharField(max_length=255, verbose_name='Contract Duration')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=50, verbose_name='Gender')),
                ('close_date', models.DateField(verbose_name='Close date')),
                ('submission_email', models.EmailField(max_length=254, null=True, verbose_name='Submission Email')),
                ('language', models.CharField(blank=True, default='English', max_length=20, null=True, verbose_name='Language')),
                ('trans_languages', models.JSONField(blank=True, default=dict, null=True)),
                ('country', models.CharField(default='Afghanistan', max_length=100, verbose_name='Country')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('years_of_experience', models.CharField(default='1 year', max_length=200, verbose_name='Years Of Experience')),
                ('education', models.CharField(default='Bachelor', max_length=255, verbose_name='Education')),
                ('description', models.TextField(verbose_name='Description')),
                ('submission_guideline', models.TextField(verbose_name='Submission Guideline')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('credit', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.employmenttype', verbose_name='Employment Type')),
            ],
        ),
    ]
