# Generated by Django 4.1 on 2024-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=50, verbose_name='Employment Type'),
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
    ]
