# Generated by Django 5.0.6 on 2024-07-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_employment_type_delete_employmenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='trans_languages',
        ),
        migrations.AddField(
            model_name='job',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='translation_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='jobs.job'),
        ),
    ]
