# Generated by Django 5.0.6 on 2024-07-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_trans_languages_job_is_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='province',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
    ]
