# Generated by Django 5.0.6 on 2024-07-07 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_city_remove_job_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='trans_languages',
        ),
        migrations.AddField(
            model_name='job',
            name='about_organization',
            field=models.TextField(blank=True, null=True, verbose_name='About the Organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='announce_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Announce Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Job Requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='translation_language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='translation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='jobs.jobcategory'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AlterField(
            model_name='job',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Close date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract Duration'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, default='Bachelor', max_length=255, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=50, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='job',
            name='no_of_jobs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Counts'),
        ),
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='submission_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Submission Email'),
        ),
        migrations.AlterField(
            model_name='job',
            name='submission_guideline',
            field=models.TextField(blank=True, null=True, verbose_name='Submission Guideline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='translation_language',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vacancy Number'),
        ),
        migrations.AlterField(
            model_name='job',
            name='years_of_experience',
            field=models.CharField(blank=True, default='1 year', max_length=200, null=True, verbose_name='Years Of Experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(to='jobs.jobcategory'),
        ),
    ]
